### ISSUE TITLE
Not published to CRAN

### ISSUE THREAD

**Issue by Kebie** [kylebutts/shiny.tailwind#12]
The install instructions do not work, not published to CRAN.

```
if (!require("devtools"))
  install.packages("devtools")
devtools::install_github("kylebutts/shiny.tailwind")
```

Works in the console though.

**Comment by kylebutts** [comment]
Hey @Kebie, Sorry about that. Been having issues getting this thing on CRAN. I just have to sit down and fix it one of these days !

**Comment by kylebutts** [comment]
All set! Thanks @DavZim for helping get this up to the edge and apologies for me being *slow* about doing the last 30 minutes of work 🤣

**Comment by DavZim** [comment]
No worries, I know the dread of trying to decipher and not being able to reproduce opague error messages from CRAN...
Happy to hear that you are making progress and congrats on this: https://cran.r-project.org/web/packages/shiny.tailwind/index.html
