### ISSUE TITLE
Additional `twXInput` helpers

### ISSUE THREAD

**Issue by DavZim** [kylebutts/shiny.tailwind#5]
In #3, you mentioned additional twInput helper functions.
I'm happy to help, which classes do you have in mind?

Shiny has the following Input classes:

*Checkbox*:
 - [x] checkboxInput
 - [x] checkboxGroupInput

*Bootstrap default*:
 - [x] fileInput
 - [x] actionButton
 - [x] actionLink

*Text Input*:
 - [x] numericInput
 - [x] passwordInput
 - [x] textInput
 - [x] textAreaInput

*Selects*:
 - [x] selectInput
 - [x] varSelectInput

*Uses External Package*:
 - [x] dateInput
 - [x] dateRangeInput
 - [x] sliderInput
 - [x] selectizeInput
 - [x] varSelectizeInput

Do we need to style all of them like textInput and selectInput? For example passwordInput is just a textInput with type password iirc.

Note that we dont need submitButton (not recommended to use by shiny) and actionButton already supports class (as does actionLink).

**Comment by kylebutts** [comment]
Yeah, I agree that the type should make it pretty easy to do a lot of the text, but I think for completeness it's worth doing. The key thing, and maybe you noticed, is that the wrapper div for most things will have the class that shiny uses to interact with
```html
<div class="form-group shiny-input-container"><div class="">...</div></div>
```

Notes: 
- `sliderInput`, `dateInput`, `dateRangeInput`, `selectizeInput`, `varSelectizeInput`,  uses an external package, so I think we should only add classes to the container div
- `actionButton` and `fileInput` use bootstrap "btn" classes, so we should remove those from the class list
- I think for extracting the select options and the checkbox options, going through the list (see how I changed `twSelectInput`) will be the more reliable methods for that

**Comment by DavZim** [comment]
Im playing around with the checkBoxInputs at the moment, and wanted to have a quick sanity check: Are we handling the label-tags correcty in [twSelectInput](https://github.com/kylebutts/shiny.tailwind/blob/master/R/twSelectInput.R#L45)? Is it `!is.null(label)` or `!is.null(label_class)`?

**Comment by kylebutts** [comment]
yes, it should be `label_class`, thanks!

**Comment by DavZim** [comment]
I am now trying to get the checkboxinput setup.
The examples I found online (eg [this](https://tailwind-elements.com/docs/standard/forms/checkbox/)) all use a div-input-label setup whereas shiny uses a div-div-label (input + span) setup. When rendered / used from shiny, they work the same.
Is this correct or should we follow the shiny styles directly?

Note that the new commit also allow disabling a checkboxinput (can be set initially, not sure about updates from shiny yet)...

Also, there is some interference with bootstrap when styling the classes using tw. But with some tweaking its fine.

``` r
library(shiny.tailwind)
library(shiny)

shiny::checkboxInput("id", "label", value = FALSE)
```
```html
<div class="form-group shiny-input-container">
  <div class="checkbox">
    <label>
      <input id="id" type="checkbox"/>
      <span>label</span>
    </label>
  </div>
</div>
````

```R
twCheckboxInput("id", "label", value = TRUE,
                container_class = "CONTAINER", label_class = "LABEL",
                input_class = "INPUT")
```
```html
<div class="form-check CONTAINER">
  <input type="checkbox" id="id" checked="" class="form-check-input INPUT"/>
  <label class="form-check-label LABEL" for="id">label</label>
</div>
```

Eg an example application:
```r
library(shiny)
# basic example
options(shiny.launch.browser = .rs.invokeShinyWindowExternal)

shinyApp(
  ui = shiny::basicPage(
  # ui = fluidPage(
    use_tailwind(tailwindConfig = "tailwind.config.js"),
    checkboxInput("id1", "Shiny Default", value = TRUE),
    twCheckboxInput(
      "id2", "TailwindCSS", value = TRUE, 
      width = "150px",
      container_class = "appearance-none pl-4 h-8 rounded-full bg-teal-100 shadow",
      input_class = "appearance-none h-4 w-4 border border-gray-300 text-red-400 focus:ring-red-200 mt-1 align-top float-left mr-2 cursor-pointer",
      label_class = "inline-block font-mono text-gray-800 pl-6"
    ),
    verbatimTextOutput("data")
  ),
  server = function(input, output) {
    output$data <- renderText({
      paste(capture.output(str(list(
        id1 = input$id1,
        id2 = input$id2
      ))), collapse ="\n")
    })
  }
)
```

![grafik](https://user-images.githubusercontent.com/15910496/172423251-6bf32ca4-1dc6-4290-b24f-d03746ce1467.png)

What irks me a bit is that the box is not centered (to you have some CSS insights?)

**Comment by kylebutts** [comment]
Yeah, it's an example of bootstrap setting things universally that are somewhat annoying. It has a top margin of 4px, so we would want to remove that presumably (as I did below)

```r
library(shiny)
library(shiny.tailwind)
# basic example
options(shiny.launch.browser = .rs.invokeShinyWindowExternal)



shinyApp(
  ui = shiny::basicPage(
    # ui = fluidPage(
    use_tailwind(),
    checkboxInput("id1", "Shiny Default", value = TRUE),
    tags$label(class="relative flex-inline items-center isolate p-4 rounded-2xl",
               tags$input(id="checkbox", type="checkbox", class="relative peer z-20 text-purple-600 rounded-md focus:ring-0", style="margin: 0px !important;"),
               tags$span(class="ml-2 relative z-20", "Checkbox Selection"),
               div(class="absolute inset-0 bg-white peer-checked:bg-purple-50 peer-checked:border-purple-300 z-10 border rounded-2xl")
    ),
    verbatimTextOutput("data")
  ),
  server = function(input, output) {
    output$data <- renderText({
      paste(capture.output(str(list(
        id1 = input$id1,
        id2 = input$id2
      ))), collapse ="\n")
    })
  }

```

![CleanShot 2022-06-07 at 10 37 31@2x](https://user-images.githubusercontent.com/19961439/172436047-2240163a-ece3-49f8-8a8e-dba017c6a46d.png)
![CleanShot 2022-06-07 at 10 37 36@2x](https://user-images.githubusercontent.com/19961439/172436076-f81d4e84-c35d-4887-9ed3-09daf65a918f.png)

**Comment by DavZim** [comment]
Uh, I love that design. Looks a lot more clear than my mockup. Maybe you should design the example apps. :)

It still looks like the actual checkbox is not in the middle but slightly at the bottom.

The question however is, do we want to have the `tw` functions as a cheap wrapper allowing to provide classes or do we want them to behave in an expected way (eg offsetting the bootstrap behavior etc). That is, should the functions follow your example and do more than just add classes?

Secondly, I see you use span in the checkbox item, should we go with this? Then I would style it like this.

**Comment by kylebutts** [comment]
Awesome, when I get a free moment, I'll do some designs for all of them and then we can make that example 4 in the package

**Comment by kylebutts** [comment]
@DavZim Here is some example forms from [here](https://flowbite.com/docs/forms/) 
https://github.com/kylebutts/shiny.tailwind/blob/master/inst/examples/04-Shiny_Inputs/app.R


<img width="1517" alt="CleanShot 2022-06-08 at 08 04 05@2x" src="https://user-images.githubusercontent.com/19961439/172636889-22c2cf75-6482-4fdd-9c76-c46f7bd38ccb.png">

**Comment by DavZim** [comment]
Should we also add a simple yet stylable tabPanel/navbarPage function?
Constructing the code manually (eg `<nav ... <ul><li class="active"><a href="#tab1"...></a></li></ul></nav>  <div class="tab-pane active" id="tab1">...</div>`) does not work as it requires missing JS code from bootstrap.
The JS Code seems simple enough (see [here](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_tabs) for a simple example).

**Comment by DavZim** [comment]
Let's close this and continue discussion in #7
